# Generated by Django 3.2.9 on 2022-02-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='block',
            name='photo',
        ),
        migrations.AlterField(
            model_name='block',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='block',
            name='view',
            field=models.ImageField(default=0, upload_to='photos/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
    ]
